# Generated by Django 4.0.4 on 2022-05-24 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Услуга')),
                ('price', models.CharField(max_length=9, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=114, verbose_name='Марка авто:')),
                ('model', models.CharField(max_length=114, verbose_name='Модель авто:')),
                ('year', models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)], verbose_name='Год автомобиля')),
                ('mileage', models.IntegerField(blank=True, help_text='Пробег авто в км', max_length=7, verbose_name='Пробег')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.maintenance', verbose_name='Рекомендуемые услуги')),
            ],
            options={
                'verbose_name': 'Рекомендуемые услуги',
                'verbose_name_plural': 'Рекомендуемые услуги',
            },
        ),
        migrations.CreateModel(
            name='DoneMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=114, verbose_name='Марка авто:')),
                ('model', models.CharField(max_length=114, verbose_name='Модель авто:')),
                ('year', models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)], verbose_name='Год автомобиля')),
                ('mileage', models.IntegerField(blank=True, help_text='Пробег авто в км', max_length=7, verbose_name='Пробег')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.maintenance', verbose_name='Предоставленные услуги')),
            ],
        ),
    ]
