# Generated by Django 4.0.4 on 2022-05-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donemaintenance',
            options={'verbose_name': 'Предоставленные услуги', 'verbose_name_plural': 'Предоставленные услуги'},
        ),
    ]
